### ISSUE TITLE
Wrong download button

### ISSUE THREAD

**Issue by RoxanaDehelean** [sebiboga/atestersmindset5#5]
**ENVIROMENT :** PROD
		Device: HP laptop										
                Browser: Chrome
		URL:  https://thesimscatalog.com/sims4/

**STEPS TO REPRODUCE :** 
    1.	Open URL browser
    2.	Cick on Furniture button
    3.	Click on See all button
    4.	Search after Single Object categories
    5.	Search after Monitor/computer + letter + clipboard + LightBox for The Sims 4

**EXPECTED RESULTS :**
	The download button should request a payment amount, in order to download the item.

**ACTUAL RESULTS:**
	The download button is availabe also without a payment amount.

**Comment by sebiboga** [comment]
I resolved this issue.
please retest

**Comment by sebiboga** [comment]
I retested the issue in QA environment
this issue has been fixed
closing the bug
